Delete Parallel.R
I think this script here causes the cyclic error when installing: 
Error : package or namespace load failed for ‘invent’ in loadNamespace(package, lib.loc):
 cyclic namespace dependency detected when loading ‘invent’, already loading ‘invent’
Error: unable to load R code in package ‘invent’
Execution halted